version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Install Backend dependencies
          command: npm run api:install
      - run:
          name: Backend Build ## builds the backend production code
          command: npm run api:build
      - run:
          name: Install Frontend dependencies 
          command: npm run frontend:install
      - run:
          name: Frontend Build ## builds the frontend production code
          command: npm run frontend:build
      - run:
          name: Backend Deploy ##adds the secrets to eb through eb cli using deploy.sh in bin folder
          command: npm run api:deploy
      - run:
          name: Frontend Deploy ## uploads media files to the s3 bucket
          command: npm run frontend:deploy

workflows:
  build:
    jobs:
      - build:
        filters:
          branches:
            only:
              - main
